"""
index_render.py - Render the auto-generated INDEX.md for a project.

Shared between scripts/validate-rules.py (which writes INDEX.md to disk)
and mcp/quality.py (which compares against on-disk INDEX.md to detect
drift). Pure: takes a list of RuleDoc and emits a string.
"""

from __future__ import annotations

from loader import RuleDoc

INDEX_HEADER = "<!-- AUTO-GENERATED by scripts/validate-rules.py - do not edit by hand. -->\n"

_GROUP_ORDER = [
    ("Workflows", "workflow"),
    ("Skills", "skill"),
    ("Patterns", "pattern"),
    ("Languages", "language-rules"),
    ("Architecture decisions", "architecture-decision"),
    ("Gates", "gate"),
]


def doc_summary(doc: RuleDoc, max_len: int = 160) -> str:
    desc = doc.metadata.get("description")
    if isinstance(desc, str) and desc.strip():
        return desc.strip()[:max_len]
    for line in doc.content.splitlines():
        s = line.strip()
        if not s or s.startswith("#") or s.startswith(">") or s.startswith("---"):
            continue
        return s[:max_len]
    return ""


def _format_entry(doc: RuleDoc) -> list[str]:
    triggers = doc.metadata.get("triggers")
    summary = doc_summary(doc)
    if isinstance(triggers, list) and triggers:
        return [
            f"- **{t}** → `{doc.relative_path}`" + (f" - {summary}" if summary else "")
            for t in triggers
            if isinstance(t, str) and t.strip()
        ]
    return [f"- `{doc.relative_path}`" + (f" - {summary}" if summary else "")]


def render_index(project_name: str, docs: list[RuleDoc]) -> str:
    """Render the canonical INDEX.md content for a project."""
    lines: list[str] = [INDEX_HEADER, f"# INDEX - {project_name}\n"]
    by_type: dict[str, list[RuleDoc]] = {}
    for d in docs:
        if d.doc_type == "other":
            continue
        if d.relative_path == "INDEX.md":
            continue
        by_type.setdefault(d.doc_type, []).append(d)

    any_section = False
    for heading, dtype in _GROUP_ORDER:
        section = sorted(by_type.get(dtype, []), key=lambda d: d.relative_path)
        if not section:
            continue
        any_section = True
        lines.append(f"## {heading}\n")
        for doc in section:
            lines.extend(_format_entry(doc))
        lines.append("")

    if not any_section:
        lines.append("_No indexed docs yet._\n")

    return "\n".join(lines).rstrip() + "\n"
